2019-02-27 21:47:07,947 [main] INFO               io.vertx.up.web.ZeroAmbient - [ ZERO ] The raw data ( node = inject ) has been detected plugin ( jooq = io.vertx.tp.plugin.jooq.JooqInfix )
2019-02-27 21:47:37,918 [main] INFO               io.vertx.up.web.ZeroAmbient - [ ZERO ] The raw data ( node = inject ) has been detected plugin ( jooq = io.vertx.tp.plugin.jooq.JooqInfix )
2019-02-27 21:48:36,824 [main] INFO               io.vertx.up.web.ZeroAmbient - [ ZERO ] The raw data ( node = inject ) has been detected plugin ( jooq = io.vertx.tp.plugin.jooq.JooqInfix )
2019-02-27 21:50:36,136 [main] INFO               io.vertx.up.web.ZeroAmbient - [ ZERO ] The raw data ( node = inject ) has been detected plugin ( jooq = io.vertx.tp.plugin.jooq.JooqInfix )
2019-02-27 21:50:37,003 [vert.x-eventloop-thread-0] WARN                    io.vertx.up.aiki.Async - java.util.concurrent.CompletionException: org.jooq.exception.DataAccessException: SQL [insert into `DB_JOOQ`.`SYS_TABULAR` (`T_COMMENT`, `S_CODE`, `S_SERIAL`, `J_CONFIG`, `IS_ACTIVE`, `Z_SIGMA`, `Z_LANGUAGE`, `Z_CREATE_BY`, `Z_CREATE_TIME`, `Z_UPDATE_BY`, `Z_UPDATE_TIME`) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]; Field 'PK_ID' doesn't have a default value
2019-02-27 21:52:17,462 [main] INFO               io.vertx.up.web.ZeroAmbient - [ ZERO ] The raw data ( node = inject ) has been detected plugin ( jooq = io.vertx.tp.plugin.jooq.JooqInfix )
2019-02-27 21:52:18,374 [vert.x-eventloop-thread-0] WARN                    io.vertx.up.aiki.Async - java.util.concurrent.CompletionException: org.jooq.exception.DataAccessException: SQL [insert into `DB_JOOQ`.`SYS_TABULAR` (`T_COMMENT`, `S_CODE`, `S_SERIAL`, `J_CONFIG`, `IS_ACTIVE`, `Z_SIGMA`, `Z_LANGUAGE`, `Z_CREATE_BY`, `Z_CREATE_TIME`, `Z_UPDATE_BY`, `Z_UPDATE_TIME`) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]; Field 'PK_ID' doesn't have a default value
2019-02-27 21:52:41,486 [main] INFO               io.vertx.up.web.ZeroAmbient - [ ZERO ] The raw data ( node = inject ) has been detected plugin ( jooq = io.vertx.tp.plugin.jooq.JooqInfix )
2019-02-27 21:52:42,400 [vert.x-eventloop-thread-0] WARN                    io.vertx.up.aiki.Async - java.util.concurrent.CompletionException: org.jooq.exception.DataAccessException: SQL [insert into `DB_JOOQ`.`SYS_TABULAR` (`T_COMMENT`, `S_CODE`, `S_SERIAL`, `J_CONFIG`, `IS_ACTIVE`, `Z_SIGMA`, `Z_LANGUAGE`, `Z_CREATE_BY`, `Z_CREATE_TIME`, `Z_UPDATE_BY`, `Z_UPDATE_TIME`) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]; Field 'PK_ID' doesn't have a default value
2019-02-27 21:53:47,083 [main] INFO               io.vertx.up.web.ZeroAmbient - [ ZERO ] The raw data ( node = inject ) has been detected plugin ( jooq = io.vertx.tp.plugin.jooq.JooqInfix )
2019-02-27 21:53:47,614 [vert.x-eventloop-thread-0] INFO                      up.god.jooq.AsyncInsertTc - [T] Normalized: {
  "S_NAME" : "「测试」Tabular",
  "S_CODE" : "TEST.CODE",
  "S_TYPE" : "jooq.test",
  "key" : "245ad5e1-2cf5-4a53-8c65-4e7fec8dab88"
}
2019-02-27 21:53:48,028 [vert.x-eventloop-thread-0] WARN                    io.vertx.up.aiki.Async - java.util.concurrent.CompletionException: org.jooq.exception.DataAccessException: SQL [insert into `DB_JOOQ`.`SYS_TABULAR` (`T_COMMENT`, `S_CODE`, `S_SERIAL`, `J_CONFIG`, `IS_ACTIVE`, `Z_SIGMA`, `Z_LANGUAGE`, `Z_CREATE_BY`, `Z_CREATE_TIME`, `Z_UPDATE_BY`, `Z_UPDATE_TIME`) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]; Field 'PK_ID' doesn't have a default value
2019-02-27 21:55:11,264 [main] INFO               io.vertx.up.web.ZeroAmbient - [ ZERO ] The raw data ( node = inject ) has been detected plugin ( jooq = io.vertx.tp.plugin.jooq.JooqInfix )
2019-02-27 21:55:11,833 [vert.x-eventloop-thread-0] INFO                      up.god.jooq.AsyncInsertTc - [T] Normalized: {
  "name" : "「测试」Tabular",
  "code" : "TEST.CODE",
  "type" : "jooq.test",
  "key" : "9e24ed41-171e-4088-bb5d-a1071360741a"
}
2019-02-27 21:55:12,222 [vert.x-eventloop-thread-0] WARN                    io.vertx.up.aiki.Async - java.util.concurrent.CompletionException: org.jooq.exception.DataAccessException: SQL [insert into `DB_JOOQ`.`SYS_TABULAR` (`T_COMMENT`, `S_CODE`, `S_SERIAL`, `J_CONFIG`, `IS_ACTIVE`, `Z_SIGMA`, `Z_LANGUAGE`, `Z_CREATE_BY`, `Z_CREATE_TIME`, `Z_UPDATE_BY`, `Z_UPDATE_TIME`) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]; Field 'PK_ID' doesn't have a default value
2019-02-27 22:00:22,355 [main] INFO               io.vertx.up.web.ZeroAmbient - [ ZERO ] The raw data ( node = inject ) has been detected plugin ( jooq = io.vertx.tp.plugin.jooq.JooqInfix )
2019-02-27 22:00:51,339 [main] INFO               io.vertx.up.web.ZeroAmbient - [ ZERO ] The raw data ( node = inject ) has been detected plugin ( jooq = io.vertx.tp.plugin.jooq.JooqInfix )
2019-02-27 22:00:51,880 [vert.x-eventloop-thread-0] INFO                      up.god.jooq.AsyncInsertTc - [T] Normalized: {
  "key" : "$GUID$",
  "name" : "「测试」Tabular",
  "code" : "TEST.CODE",
  "type" : "jooq.test"
}
2019-02-27 22:00:52,238 [vert.x-eventloop-thread-0] WARN                    io.vertx.up.aiki.Async - java.util.concurrent.CompletionException: org.jooq.exception.DataAccessException: SQL [insert into `DB_JOOQ`.`SYS_TABULAR` (`T_COMMENT`, `S_CODE`, `S_SERIAL`, `J_CONFIG`, `IS_ACTIVE`, `Z_SIGMA`, `Z_LANGUAGE`, `Z_CREATE_BY`, `Z_CREATE_TIME`, `Z_UPDATE_BY`, `Z_UPDATE_TIME`) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]; Field 'PK_ID' doesn't have a default value
2019-02-27 22:05:28,754 [main] INFO               io.vertx.up.web.ZeroAmbient - [ ZERO ] The raw data ( node = inject ) has been detected plugin ( jooq = io.vertx.tp.plugin.jooq.JooqInfix )
2019-02-27 22:05:29,206 [vert.x-eventloop-thread-0] INFO                      up.god.jooq.AsyncInsertTc - [T] Normalized: {
  "key" : "c6a026cc-ede6-42aa-b54b-4a3132d5566b",
  "name" : "「测试」Tabular",
  "code" : "TEST.CODE",
  "type" : "jooq.test"
}
2019-02-27 22:05:29,630 [vert.x-eventloop-thread-0] WARN                    io.vertx.up.aiki.Async - java.util.concurrent.CompletionException: org.jooq.exception.DataAccessException: SQL [insert into `DB_JOOQ`.`SYS_TABULAR` (`PK_ID`, `T_COMMENT`, `S_NAME`, `S_CODE`, `S_SERIAL`, `S_TYPE`, `J_CONFIG`, `IS_ACTIVE`, `Z_SIGMA`, `Z_LANGUAGE`, `Z_CREATE_BY`, `Z_CREATE_TIME`, `Z_UPDATE_BY`, `Z_UPDATE_TIME`) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]; Field 'I_ORDER' doesn't have a default value
2019-02-27 22:06:19,170 [main] INFO               io.vertx.up.web.ZeroAmbient - [ ZERO ] The raw data ( node = inject ) has been detected plugin ( jooq = io.vertx.tp.plugin.jooq.JooqInfix )
2019-02-27 22:06:19,623 [vert.x-eventloop-thread-0] INFO                      up.god.jooq.AsyncInsertTc - [T] Normalized: {
  "key" : "5b29245a-7a03-4157-81b8-dbf8cd48a8f2",
  "name" : "「测试」Tabular",
  "code" : "TEST.CODE",
  "type" : "jooq.test",
  "order" : 2,
  "active" : true,
  "sigma" : "test-jooq",
  "language" : "cn"
}
2019-02-27 22:15:25,985 [main] INFO               io.vertx.up.web.ZeroAmbient - [ ZERO ] The raw data ( node = inject ) has been detected plugin ( jooq = io.vertx.tp.plugin.jooq.JooqInfix )
2019-02-27 22:21:11,724 [main] INFO               io.vertx.up.web.ZeroAmbient - [ ZERO ] The raw data ( node = inject ) has been detected plugin ( jooq = io.vertx.tp.plugin.jooq.JooqInfix )
2019-02-27 22:21:23,834 [main] INFO               io.vertx.up.web.ZeroAmbient - [ ZERO ] The raw data ( node = inject ) has been detected plugin ( jooq = io.vertx.tp.plugin.jooq.JooqInfix )
2019-02-27 22:21:28,263 [main] ERROR        com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Exception during pool initialization.
java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:905)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:830)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:455)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:240)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:353)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:562)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at io.vertx.tp.hikari.config.HikariCpConfig.<init>(HikariCpConfig.java:29)
	at io.vertx.tp.hikari.config.HikariCpConfig.create(HikariCpConfig.java:37)
	at io.vertx.tp.hikari.HikariCpPool.lambda$getConnection$4(HikariCpPool.java:40)
	at io.zero.epic.fn.Zero.getJvm(Zero.java:69)
	at io.zero.epic.fn.Fn.getJvm(Fn.java:309)
	at io.vertx.tp.hikari.HikariCpPool.getConnection(HikariCpPool.java:40)
	at io.vertx.tp.plugin.jooq.JooqInfix.lambda$null$0(JooqInfix.java:45)
	at io.vertx.up.plugin.Infix.init(Infix.java:53)
	at io.vertx.up.plugin.Infix.init(Infix.java:32)
	at io.vertx.tp.plugin.jooq.JooqInfix.lambda$initInternal$1(JooqInfix.java:39)
	at io.zero.epic.fn.Pond.exec(Pond.java:28)
	at io.zero.epic.fn.Fn.pool(Fn.java:425)
	at io.vertx.tp.plugin.jooq.JooqInfix.initInternal(JooqInfix.java:38)
	at io.vertx.tp.plugin.jooq.JooqInfix.init(JooqInfix.java:55)
	at up.god.jooq.JooqTc.setUp(JooqTc.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.vertx.ext.unit.junit.VertxUnitRunner.invokeTestMethod(VertxUnitRunner.java:93)
	at io.vertx.ext.unit.junit.VertxUnitRunner.lambda$invokeExplosively$0(VertxUnitRunner.java:114)
	at io.vertx.ext.unit.impl.TestContextImpl.run(TestContextImpl.java:90)
	at io.vertx.ext.unit.junit.VertxUnitRunner.invokeExplosively(VertxUnitRunner.java:130)
	at io.vertx.ext.unit.junit.VertxUnitRunner.access$000(VertxUnitRunner.java:39)
	at io.vertx.ext.unit.junit.VertxUnitRunner$2.evaluate(VertxUnitRunner.java:194)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: com.mysql.cj.exceptions.CJException: Unknown database 'db_jooqe'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129)
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:816)
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:741)
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:709)
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:132)
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:540)
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:202)
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1449)
	at com.mysql.cj.NativeSession.connect(NativeSession.java:165)
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:849)
	... 42 common frames omitted
2019-02-27 22:25:07,021 [main] INFO               io.vertx.up.web.ZeroAmbient - [ ZERO ] The raw data ( node = inject ) has been detected plugin ( jooq = io.vertx.tp.plugin.jooq.JooqInfix )
2019-02-27 22:25:11,456 [main] ERROR        com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Exception during pool initialization.
java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:905)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:830)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:455)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:240)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:353)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:562)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at io.vertx.tp.hikari.config.HikariCpConfig.<init>(HikariCpConfig.java:29)
	at io.vertx.tp.hikari.config.HikariCpConfig.create(HikariCpConfig.java:37)
	at io.vertx.tp.hikari.HikariCpPool.lambda$getConnection$4(HikariCpPool.java:40)
	at io.zero.epic.fn.Zero.getJvm(Zero.java:69)
	at io.zero.epic.fn.Fn.getJvm(Fn.java:309)
	at io.vertx.tp.hikari.HikariCpPool.getConnection(HikariCpPool.java:40)
	at io.vertx.tp.plugin.jooq.JooqInfix.lambda$null$0(JooqInfix.java:45)
	at io.vertx.up.plugin.Infix.init(Infix.java:53)
	at io.vertx.up.plugin.Infix.init(Infix.java:32)
	at io.vertx.tp.plugin.jooq.JooqInfix.lambda$initInternal$1(JooqInfix.java:39)
	at io.zero.epic.fn.Pond.exec(Pond.java:28)
	at io.zero.epic.fn.Fn.pool(Fn.java:425)
	at io.vertx.tp.plugin.jooq.JooqInfix.initInternal(JooqInfix.java:38)
	at io.vertx.tp.plugin.jooq.JooqInfix.init(JooqInfix.java:55)
	at up.god.jooq.JooqTc.setUp(JooqTc.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.vertx.ext.unit.junit.VertxUnitRunner.invokeTestMethod(VertxUnitRunner.java:93)
	at io.vertx.ext.unit.junit.VertxUnitRunner.lambda$invokeExplosively$0(VertxUnitRunner.java:114)
	at io.vertx.ext.unit.impl.TestContextImpl.run(TestContextImpl.java:90)
	at io.vertx.ext.unit.junit.VertxUnitRunner.invokeExplosively(VertxUnitRunner.java:130)
	at io.vertx.ext.unit.junit.VertxUnitRunner.access$000(VertxUnitRunner.java:39)
	at io.vertx.ext.unit.junit.VertxUnitRunner$2.evaluate(VertxUnitRunner.java:194)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: com.mysql.cj.exceptions.CJException: Unknown database 'db_jooqe'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129)
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:816)
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:741)
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:709)
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:132)
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:540)
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:202)
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1449)
	at com.mysql.cj.NativeSession.connect(NativeSession.java:165)
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:849)
	... 42 common frames omitted
2019-02-27 22:25:11,475 [main] WARN                        up.god.jooq.JooqTc - io.vertx.tp.error.DataSourceException: [ERR-40056] (HikariCpConfig) ZeroException occus: (Database) Data pool initialized met issue, jdbcUrl = jdbc:mysql://127.0.0.1:3306/DB_JOOQE?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&useSSL=false, exception = Failed to initialize pool: Could not create connection to database server. Attempted reconnect 3 times. Giving up..
2019-02-27 22:25:11,491 [vert.x-eventloop-thread-0] INFO                 up.god.jooq.AsyncInsertTc - [ ZERO Test ] Test input up.god.file: test/up.god.jooq/pojo.json
2019-02-27 22:25:11,510 [vert.x-eventloop-thread-0] INFO                 up.god.jooq.AsyncInsertTc - [T] Normalized: {
  "key" : "1dc1f369-7487-414d-952e-d44ad4a0cd82",
  "name" : "「测试」Tabular",
  "code" : "TEST.CODE",
  "type" : "jooq.test",
  "order" : 2,
  "active" : true,
  "sigma" : "test-jooq",
  "language" : "cn"
}
2019-02-27 22:26:11,787 [main] INFO               io.vertx.up.web.ZeroAmbient - [ ZERO ] The raw data ( node = inject ) has been detected plugin ( jooq = io.vertx.tp.plugin.jooq.JooqInfix )
2019-02-27 22:26:16,208 [main] ERROR        com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Exception during pool initialization.
java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:905)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:830)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:455)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:240)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:353)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:562)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at io.vertx.tp.hikari.config.HikariCpConfig.<init>(HikariCpConfig.java:29)
	at io.vertx.tp.hikari.config.HikariCpConfig.create(HikariCpConfig.java:37)
	at io.vertx.tp.hikari.HikariCpPool.lambda$getConnection$4(HikariCpPool.java:40)
	at io.zero.epic.fn.Zero.getJvm(Zero.java:69)
	at io.zero.epic.fn.Fn.getJvm(Fn.java:309)
	at io.vertx.tp.hikari.HikariCpPool.getConnection(HikariCpPool.java:40)
	at io.vertx.tp.plugin.jooq.JooqInfix.lambda$null$0(JooqInfix.java:45)
	at io.vertx.up.plugin.Infix.init(Infix.java:53)
	at io.vertx.up.plugin.Infix.init(Infix.java:32)
	at io.vertx.tp.plugin.jooq.JooqInfix.lambda$initInternal$1(JooqInfix.java:39)
	at io.zero.epic.fn.Pond.exec(Pond.java:28)
	at io.zero.epic.fn.Fn.pool(Fn.java:425)
	at io.vertx.tp.plugin.jooq.JooqInfix.initInternal(JooqInfix.java:38)
	at io.vertx.tp.plugin.jooq.JooqInfix.init(JooqInfix.java:55)
	at up.god.jooq.JooqTc.setUp(JooqTc.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.vertx.ext.unit.junit.VertxUnitRunner.invokeTestMethod(VertxUnitRunner.java:93)
	at io.vertx.ext.unit.junit.VertxUnitRunner.lambda$invokeExplosively$0(VertxUnitRunner.java:114)
	at io.vertx.ext.unit.impl.TestContextImpl.run(TestContextImpl.java:90)
	at io.vertx.ext.unit.junit.VertxUnitRunner.invokeExplosively(VertxUnitRunner.java:130)
	at io.vertx.ext.unit.junit.VertxUnitRunner.access$000(VertxUnitRunner.java:39)
	at io.vertx.ext.unit.junit.VertxUnitRunner$2.evaluate(VertxUnitRunner.java:194)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: com.mysql.cj.exceptions.CJException: Unknown database 'db_jooqe'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129)
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:816)
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:741)
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:709)
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:132)
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:540)
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:202)
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1449)
	at com.mysql.cj.NativeSession.connect(NativeSession.java:165)
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:849)
	... 42 common frames omitted
2019-02-27 22:26:16,222 [main] WARN                        up.god.jooq.JooqTc - io.vertx.tp.error.DataSourceException: [ERR-40056] (HikariCpConfig) ZeroException occus: (Database) Data pool initialized met issue, jdbcUrl = jdbc:mysql://127.0.0.1:3306/DB_JOOQE?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&useSSL=false, exception = Failed to initialize pool: Could not create connection to database server. Attempted reconnect 3 times. Giving up..
2019-02-27 22:26:16,237 [vert.x-eventloop-thread-0] INFO                 up.god.jooq.AsyncInsertTc - [ ZERO Test ] Test input up.god.file: test/up.god.jooq/pojo.json
2019-02-27 22:26:16,256 [vert.x-eventloop-thread-0] INFO                 up.god.jooq.AsyncInsertTc - [T] Normalized: {
  "key" : "762d4076-1589-48e4-9e82-b4fa8dbda18f",
  "name" : "「测试」Tabular",
  "code" : "TEST.CODE",
  "type" : "jooq.test",
  "order" : 2,
  "active" : true,
  "sigma" : "test-jooq",
  "language" : "cn"
}
2019-02-27 22:31:08,563 [main] INFO               io.vertx.up.web.ZeroAmbient - [ ZERO ] The raw data ( node = inject ) has been detected plugin ( jooq = io.vertx.tp.plugin.jooq.JooqInfix )
2019-02-27 22:31:12,986 [main] ERROR        com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Exception during pool initialization.
java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:905)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:830)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:455)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:240)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:353)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:562)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at io.vertx.tp.hikari.config.HikariCpConfig.<init>(HikariCpConfig.java:29)
	at io.vertx.tp.hikari.config.HikariCpConfig.create(HikariCpConfig.java:37)
	at io.vertx.tp.hikari.HikariCpPool.lambda$getConnection$4(HikariCpPool.java:40)
	at io.zero.epic.fn.Zero.getJvm(Zero.java:69)
	at io.zero.epic.fn.Fn.getJvm(Fn.java:309)
	at io.vertx.tp.hikari.HikariCpPool.getConnection(HikariCpPool.java:40)
	at io.vertx.tp.plugin.jooq.JooqInfix.lambda$null$0(JooqInfix.java:45)
	at io.vertx.up.plugin.Infix.init(Infix.java:53)
	at io.vertx.up.plugin.Infix.init(Infix.java:32)
	at io.vertx.tp.plugin.jooq.JooqInfix.lambda$initInternal$1(JooqInfix.java:39)
	at io.zero.epic.fn.Pond.exec(Pond.java:28)
	at io.zero.epic.fn.Fn.pool(Fn.java:425)
	at io.vertx.tp.plugin.jooq.JooqInfix.initInternal(JooqInfix.java:38)
	at io.vertx.tp.plugin.jooq.JooqInfix.init(JooqInfix.java:55)
	at up.god.jooq.JooqTc.setUp(JooqTc.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.vertx.ext.unit.junit.VertxUnitRunner.invokeTestMethod(VertxUnitRunner.java:93)
	at io.vertx.ext.unit.junit.VertxUnitRunner.lambda$invokeExplosively$0(VertxUnitRunner.java:114)
	at io.vertx.ext.unit.impl.TestContextImpl.run(TestContextImpl.java:90)
	at io.vertx.ext.unit.junit.VertxUnitRunner.invokeExplosively(VertxUnitRunner.java:130)
	at io.vertx.ext.unit.junit.VertxUnitRunner.access$000(VertxUnitRunner.java:39)
	at io.vertx.ext.unit.junit.VertxUnitRunner$2.evaluate(VertxUnitRunner.java:194)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: com.mysql.cj.exceptions.CJException: Unknown database 'db_jooqe'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129)
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:816)
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:741)
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:709)
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:132)
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:540)
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:202)
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1449)
	at com.mysql.cj.NativeSession.connect(NativeSession.java:165)
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:849)
	... 42 common frames omitted
2019-02-27 22:31:13,003 [main] WARN                        up.god.jooq.JooqTc - io.vertx.tp.error.DataSourceException: [ERR-40056] (HikariCpConfig) ZeroException occus: (Database) Data pool initialized met issue, jdbcUrl = jdbc:mysql://127.0.0.1:3306/DB_JOOQE?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&useSSL=false, exception = Failed to initialize pool: Could not create connection to database server. Attempted reconnect 3 times. Giving up..
2019-02-27 22:31:13,021 [vert.x-eventloop-thread-0] INFO                 up.god.jooq.AsyncInsertTc - [ ZERO Test ] Test input up.god.file: test/up.god.jooq/pojo.json
2019-02-27 22:31:13,046 [vert.x-eventloop-thread-0] INFO                 up.god.jooq.AsyncInsertTc - [T] Normalized: {
  "key" : "01415bc6-1452-4862-8b8b-1a33c393d906",
  "name" : "「测试」Tabular",
  "code" : "TEST.CODE",
  "type" : "jooq.test",
  "order" : 2,
  "active" : true,
  "sigma" : "test-jooq",
  "language" : "cn"
}
2019-02-27 22:33:12,741 [main] INFO               io.vertx.up.web.ZeroAmbient - [ ZERO ] The raw data ( node = inject ) has been detected plugin ( jooq = io.vertx.tp.plugin.jooq.JooqInfix )
2019-02-27 22:33:17,184 [main] ERROR        com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Exception during pool initialization.
java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:905)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:830)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:455)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:240)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:353)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:562)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at io.vertx.tp.hikari.config.HikariCpConfig.<init>(HikariCpConfig.java:29)
	at io.vertx.tp.hikari.config.HikariCpConfig.create(HikariCpConfig.java:37)
	at io.vertx.tp.hikari.HikariCpPool.lambda$getConnection$4(HikariCpPool.java:40)
	at io.zero.epic.fn.Zero.getJvm(Zero.java:69)
	at io.zero.epic.fn.Fn.getJvm(Fn.java:309)
	at io.vertx.tp.hikari.HikariCpPool.getConnection(HikariCpPool.java:40)
	at io.vertx.tp.plugin.jooq.JooqInfix.lambda$null$0(JooqInfix.java:45)
	at io.vertx.up.plugin.Infix.init(Infix.java:53)
	at io.vertx.up.plugin.Infix.init(Infix.java:32)
	at io.vertx.tp.plugin.jooq.JooqInfix.lambda$initInternal$1(JooqInfix.java:39)
	at io.zero.epic.fn.Pond.exec(Pond.java:28)
	at io.zero.epic.fn.Fn.pool(Fn.java:425)
	at io.vertx.tp.plugin.jooq.JooqInfix.initInternal(JooqInfix.java:38)
	at io.vertx.tp.plugin.jooq.JooqInfix.init(JooqInfix.java:55)
	at up.god.jooq.JooqTc.setUp(JooqTc.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.vertx.ext.unit.junit.VertxUnitRunner.invokeTestMethod(VertxUnitRunner.java:93)
	at io.vertx.ext.unit.junit.VertxUnitRunner.lambda$invokeExplosively$0(VertxUnitRunner.java:114)
	at io.vertx.ext.unit.impl.TestContextImpl.run(TestContextImpl.java:90)
	at io.vertx.ext.unit.junit.VertxUnitRunner.invokeExplosively(VertxUnitRunner.java:130)
	at io.vertx.ext.unit.junit.VertxUnitRunner.access$000(VertxUnitRunner.java:39)
	at io.vertx.ext.unit.junit.VertxUnitRunner$2.evaluate(VertxUnitRunner.java:194)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: com.mysql.cj.exceptions.CJException: Unknown database 'db_jooqe'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129)
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:816)
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:741)
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:709)
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:132)
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:540)
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:202)
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1449)
	at com.mysql.cj.NativeSession.connect(NativeSession.java:165)
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:849)
	... 42 common frames omitted
2019-02-27 22:33:17,202 [main] WARN                        up.god.jooq.JooqTc - io.vertx.tp.error.DataSourceException: [ERR-40056] (HikariCpConfig) ZeroException occus: (Database) Data pool initialized met issue, jdbcUrl = jdbc:mysql://127.0.0.1:3306/DB_JOOQE?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&useSSL=false, exception = Failed to initialize pool: Could not create connection to database server. Attempted reconnect 3 times. Giving up..
2019-02-27 22:33:17,219 [vert.x-eventloop-thread-0] INFO                 up.god.jooq.AsyncInsertTc - [ ZERO Test ] Test input up.god.file: test/up.god.jooq/pojo.json
2019-02-27 22:33:17,243 [vert.x-eventloop-thread-0] INFO                 up.god.jooq.AsyncInsertTc - [T] Normalized: {
  "key" : "52c9178e-90f0-4962-bbf1-e5c0f07afd1f",
  "name" : "「测试」Tabular",
  "code" : "TEST.CODE",
  "type" : "jooq.test",
  "order" : 2,
  "active" : true,
  "sigma" : "test-jooq",
  "language" : "cn"
}
2019-02-27 22:36:11,191 [main] INFO               io.vertx.up.web.ZeroAmbient - [ ZERO ] The raw data ( node = inject ) has been detected plugin ( jooq = io.vertx.tp.plugin.jooq.JooqInfix )
2019-02-27 22:36:11,632 [vert.x-eventloop-thread-0] INFO                 up.god.jooq.AsyncInsertTc - [ ZERO Test ] Test input up.god.file: test/up.god.jooq/pojo.json
2019-02-27 22:36:11,651 [vert.x-eventloop-thread-0] INFO                 up.god.jooq.AsyncInsertTc - [T] Normalized: {
  "key" : "524166cd-1dc5-4afc-8aa5-93db4b7bc69e",
  "name" : "「测试」Tabular",
  "code" : "TEST.CODE",
  "type" : "jooq.test",
  "order" : 2,
  "active" : true,
  "sigma" : "test-jooq",
  "language" : "cn"
}
2019-02-27 22:36:12,080 [vert.x-eventloop-thread-0] WARN                    io.vertx.up.aiki.Async - java.util.concurrent.CompletionException: org.jooq.exception.DataAccessException: SQL [insert into `DB_JOOQ`.`SYS_TABULAR` (`PK_ID`, `T_COMMENT`, `S_NAME`, `S_CODE`, `S_SERIAL`, `S_TYPE`, `J_CONFIG`, `I_ORDER`, `IS_ACTIVE`, `Z_SIGMA`, `Z_LANGUAGE`, `Z_CREATE_BY`, `Z_CREATE_TIME`, `Z_UPDATE_BY`, `Z_UPDATE_TIME`) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]; Duplicate entry 'TEST.CODE-jooq.test-test-jooq-cn' for key 'UK_SYS_TABULAR_S_CODE_S_TYPE_Z_SIGMA_Z_LANGUAGE'
2019-02-27 22:36:59,890 [main] INFO               io.vertx.up.web.ZeroAmbient - [ ZERO ] The raw data ( node = inject ) has been detected plugin ( jooq = io.vertx.tp.plugin.jooq.JooqInfix )
2019-02-27 22:37:00,368 [vert.x-eventloop-thread-0] INFO                 up.god.jooq.AsyncInsertTc - [ ZERO Test ] Test input up.god.file: test/up.god.jooq/pojo.json
2019-02-27 22:37:00,387 [vert.x-eventloop-thread-0] INFO                 up.god.jooq.AsyncInsertTc - [T] Normalized: {
  "key" : "1b072f90-5647-4d97-8ad4-e2af8fb47882",
  "name" : "「测试」Tabular",
  "code" : "64bfb25a-705a-41dd-ad77-606f681b4bbd",
  "type" : "jooq.test",
  "order" : 2,
  "active" : true,
  "sigma" : "test-jooq",
  "language" : "cn"
}
2019-02-27 22:37:30,307 [main] INFO               io.vertx.up.web.ZeroAmbient - [ ZERO ] The raw data ( node = inject ) has been detected plugin ( jooq = io.vertx.tp.plugin.jooq.JooqInfix )
2019-02-27 22:37:30,768 [vert.x-eventloop-thread-0] INFO                 up.god.jooq.AsyncInsertTc - [ ZERO Test ] Test input up.god.file: test/up.god.jooq/pojo.json
2019-02-27 22:37:30,787 [vert.x-eventloop-thread-0] INFO                 up.god.jooq.AsyncInsertTc - [T] Normalized: {
  "key" : "e467320e-270d-475a-b44b-3e74bdad429e",
  "name" : "「测试」Tabular",
  "code" : "01d77b72-82bf-42cc-90fe-a0e0445b2008",
  "type" : "jooq.test",
  "order" : 2,
  "active" : true,
  "sigma" : "test-jooq",
  "language" : "cn"
}
2019-02-27 22:38:13,463 [main] INFO               io.vertx.up.web.ZeroAmbient - [ ZERO ] The raw data ( node = inject ) has been detected plugin ( jooq = io.vertx.tp.plugin.jooq.JooqInfix )
2019-02-27 22:38:13,903 [vert.x-eventloop-thread-0] INFO                 up.god.jooq.AsyncInsertTc - [ ZERO Test ] Test input up.god.file: test/up.god.jooq/pojo.json
2019-02-27 22:38:13,923 [vert.x-eventloop-thread-0] INFO                 up.god.jooq.AsyncInsertTc - [T] Normalized: {
  "key" : "037a830c-7692-4e6b-a658-fb3e6d1ffec9",
  "name" : "「测试」Tabular",
  "code" : "b1c98b30-fc96-464e-bb60-21803b0a4033",
  "type" : "jooq.test",
  "order" : 2,
  "active" : true,
  "sigma" : "test-jooq",
  "language" : "cn"
}
