2019-06-11 15:31:10,837 [main] INFO               io.vertx.up.web.ZeroAmbient - [ ZERO ] The raw data ( node = inject ) has been detected plugin ( jooq = io.vertx.tp.plugin.jooq.JooqInfix )
2019-06-11 15:31:15,348 [main] ERROR        com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Exception during pool initialization.
java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:905)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:830)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:455)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:240)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:353)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:562)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at io.vertx.tp.hikari.config.HikariCpConfig.<init>(HikariCpConfig.java:29)
	at io.vertx.tp.hikari.config.HikariCpConfig.create(HikariCpConfig.java:37)
	at io.vertx.tp.hikari.HikariCpPool.lambda$getConnection$4(HikariCpPool.java:40)
	at io.zero.epic.fn.Zero.getJvm(Zero.java:69)
	at io.zero.epic.fn.Fn.getJvm(Fn.java:322)
	at io.vertx.tp.hikari.HikariCpPool.getConnection(HikariCpPool.java:40)
	at io.vertx.tp.plugin.jooq.JooqInfix.lambda$null$0(JooqInfix.java:45)
	at io.vertx.up.plugin.Infix.init(Infix.java:53)
	at io.vertx.up.plugin.Infix.init(Infix.java:32)
	at io.vertx.tp.plugin.jooq.JooqInfix.lambda$initInternal$1(JooqInfix.java:39)
	at io.zero.epic.fn.Pond.exec(Pond.java:28)
	at io.zero.epic.fn.Fn.pool(Fn.java:438)
	at io.vertx.tp.plugin.jooq.JooqInfix.initInternal(JooqInfix.java:38)
	at io.vertx.tp.plugin.jooq.JooqInfix.init(JooqInfix.java:55)
	at up.god.jooq.JooqTc.setUp(JooqTc.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.vertx.ext.unit.junit.VertxUnitRunner.invokeTestMethod(VertxUnitRunner.java:93)
	at io.vertx.ext.unit.junit.VertxUnitRunner.lambda$invokeExplosively$0(VertxUnitRunner.java:114)
	at io.vertx.ext.unit.impl.TestContextImpl.run(TestContextImpl.java:90)
	at io.vertx.ext.unit.junit.VertxUnitRunner.invokeExplosively(VertxUnitRunner.java:130)
	at io.vertx.ext.unit.junit.VertxUnitRunner.access$000(VertxUnitRunner.java:39)
	at io.vertx.ext.unit.junit.VertxUnitRunner$2.evaluate(VertxUnitRunner.java:194)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:379)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:340)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:413)
Caused by: com.mysql.cj.exceptions.CJException: Unknown database 'db_jooq'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129)
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:816)
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:741)
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:709)
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:132)
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:540)
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:202)
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1452)
	at com.mysql.cj.NativeSession.connect(NativeSession.java:165)
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:849)
	... 45 common frames omitted
2019-06-11 15:31:15,371 [main] WARN                        up.god.jooq.JooqTc - io.vertx.tp.error.DataSourceException: [ERR-40056] (HikariCpConfig) ZeroException occus: (Database) Data pool initialized met issue, jdbcUrl = jdbc:mysql://127.0.0.1:3306/DB_JOOQ?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&useSSL=false, exception = Failed to initialize pool: Could not create connection to database server. Attempted reconnect 3 times. Giving up..
2019-06-11 15:31:15,392 [vert.x-eventloop-thread-0] INFO                 up.god.jooq.AsyncInsertTc - [ ZERO Test ] Test input up.god.file: test/up.god.jooq/pojo.json
2019-06-11 15:31:15,415 [vert.x-eventloop-thread-0] INFO                 up.god.jooq.AsyncInsertTc - [T] Normalized: {
  "key" : "24c6cf4d-75a3-4663-9846-dde762a7bae3",
  "name" : "「测试」Tabular",
  "code" : "ecbdf556-0c5d-4d14-bc3d-b3650f0886fb",
  "type" : "jooq.test",
  "order" : 2,
  "active" : true,
  "sigma" : "test-jooq",
  "language" : "cn"
}
